/*
 * generated by Xtext 2.15.0
 */
package wizard.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import wizard.texteditor.ui.internal.TexteditorActivator;

public class WizardUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TexteditorActivator.getInstance().getInjector("wizard.Wizard");
	}

}
