/**
 * generated by Xtext 2.15.0
 */
package wizard.ide;

import wizard.ide.AbstractWizardIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WizardIdeModule extends AbstractWizardIdeModule {
}
