/**
 * generated by Xtext 2.15.0
 */
package wizard.validation;

import wizard.validation.AbstractWizardValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WizardValidator extends AbstractWizardValidator {
}
