/*
 * generated by Xtext 2.15.0
 */
package wizard.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class WizardGrammarAccess extends AbstractGrammarElementFinder {
	
	public class WizardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Wizard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWizardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTituloAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTituloEStringParserRuleCall_1_0 = (RuleCall)cTituloAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPaginasKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPaginasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPaginasPaginaParserRuleCall_4_0 = (RuleCall)cPaginasAssignment_4.eContents().get(0);
		private final Keyword cInicialKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPagIniAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cPagIniPaginaCrossReference_6_0 = (CrossReference)cPagIniAssignment_6.eContents().get(0);
		private final RuleCall cPagIniPaginaEStringParserRuleCall_6_0_1 = (RuleCall)cPagIniPaginaCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Wizard:
		//	'Wizard' titulo=EString
		//	'{'
		//	'Paginas:'
		//	paginas+=Pagina+
		//	'inicial' pagIni=[Pagina|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Wizard' titulo=EString '{' 'Paginas:' paginas+=Pagina+ 'inicial' pagIni=[Pagina|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Wizard'
		public Keyword getWizardKeyword_0() { return cWizardKeyword_0; }
		
		//titulo=EString
		public Assignment getTituloAssignment_1() { return cTituloAssignment_1; }
		
		//EString
		public RuleCall getTituloEStringParserRuleCall_1_0() { return cTituloEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'Paginas:'
		public Keyword getPaginasKeyword_3() { return cPaginasKeyword_3; }
		
		//paginas+=Pagina+
		public Assignment getPaginasAssignment_4() { return cPaginasAssignment_4; }
		
		//Pagina
		public RuleCall getPaginasPaginaParserRuleCall_4_0() { return cPaginasPaginaParserRuleCall_4_0; }
		
		//'inicial'
		public Keyword getInicialKeyword_5() { return cInicialKeyword_5; }
		
		//pagIni=[Pagina|EString]
		public Assignment getPagIniAssignment_6() { return cPagIniAssignment_6; }
		
		//[Pagina|EString]
		public CrossReference getPagIniPaginaCrossReference_6_0() { return cPagIniPaginaCrossReference_6_0; }
		
		//EString
		public RuleCall getPagIniPaginaEStringParserRuleCall_6_0_1() { return cPagIniPaginaEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class BotonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Boton");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cBotonKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cNavegarKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final RuleCall cBotonNavegarParserRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cBotonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cMensajeKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cBotonMensajeParserRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cBotonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cCerrarKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final RuleCall cBotonCerrarParserRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		
		//Boton:
		//	"Boton" "navegar" BotonNavegar | "Boton" "mensaje" BotonMensaje | "Boton" "cerrar" BotonCerrar;
		@Override public ParserRule getRule() { return rule; }
		
		//"Boton" "navegar" BotonNavegar | "Boton" "mensaje" BotonMensaje | "Boton" "cerrar" BotonCerrar
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"Boton" "navegar" BotonNavegar
		public Group getGroup_0() { return cGroup_0; }
		
		//"Boton"
		public Keyword getBotonKeyword_0_0() { return cBotonKeyword_0_0; }
		
		//"navegar"
		public Keyword getNavegarKeyword_0_1() { return cNavegarKeyword_0_1; }
		
		//BotonNavegar
		public RuleCall getBotonNavegarParserRuleCall_0_2() { return cBotonNavegarParserRuleCall_0_2; }
		
		//"Boton" "mensaje" BotonMensaje
		public Group getGroup_1() { return cGroup_1; }
		
		//"Boton"
		public Keyword getBotonKeyword_1_0() { return cBotonKeyword_1_0; }
		
		//"mensaje"
		public Keyword getMensajeKeyword_1_1() { return cMensajeKeyword_1_1; }
		
		//BotonMensaje
		public RuleCall getBotonMensajeParserRuleCall_1_2() { return cBotonMensajeParserRuleCall_1_2; }
		
		//"Boton" "cerrar" BotonCerrar
		public Group getGroup_2() { return cGroup_2; }
		
		//"Boton"
		public Keyword getBotonKeyword_2_0() { return cBotonKeyword_2_0; }
		
		//"cerrar"
		public Keyword getCerrarKeyword_2_1() { return cCerrarKeyword_2_1; }
		
		//BotonCerrar
		public RuleCall getBotonCerrarParserRuleCall_2_2() { return cBotonCerrarParserRuleCall_2_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PaginaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Pagina");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPaginaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCamposKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCamposTextoAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCamposTextoCampoTextoParserRuleCall_3_2_0 = (RuleCall)cCamposTextoAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCamposTextoAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCamposTextoCampoTextoParserRuleCall_3_3_1_0 = (RuleCall)cCamposTextoAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCasillasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCasillasVerifAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCasillasVerifCasillaVerifParserRuleCall_4_2_0 = (RuleCall)cCasillasVerifAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCasillasVerifAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCasillasVerifCasillaVerifParserRuleCall_4_3_1_0 = (RuleCall)cCasillasVerifAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cBotonesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cBotonesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cBotonesBotonParserRuleCall_7_0 = (RuleCall)cBotonesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cBotonesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cBotonesBotonParserRuleCall_8_1_0 = (RuleCall)cBotonesAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cSemicolonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Pagina:
		//	'Pagina'
		//	name=EString
		//	':' ('campos' '{' camposTexto+=CampoTexto ("," camposTexto+=CampoTexto)* '}')? ('casillas' '{'
		//	casillasVerif+=CasillaVerif ("," casillasVerif+=CasillaVerif)* '}')?
		//	'botones' '{' botones+=Boton ("," botones+=Boton)* '}'
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//'Pagina' name=EString ':' ('campos' '{' camposTexto+=CampoTexto ("," camposTexto+=CampoTexto)* '}')? ('casillas' '{'
		//casillasVerif+=CasillaVerif ("," casillasVerif+=CasillaVerif)* '}')? 'botones' '{' botones+=Boton (","
		//botones+=Boton)* '}' ';'
		public Group getGroup() { return cGroup; }
		
		//'Pagina'
		public Keyword getPaginaKeyword_0() { return cPaginaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//('campos' '{' camposTexto+=CampoTexto ("," camposTexto+=CampoTexto)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'campos'
		public Keyword getCamposKeyword_3_0() { return cCamposKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//camposTexto+=CampoTexto
		public Assignment getCamposTextoAssignment_3_2() { return cCamposTextoAssignment_3_2; }
		
		//CampoTexto
		public RuleCall getCamposTextoCampoTextoParserRuleCall_3_2_0() { return cCamposTextoCampoTextoParserRuleCall_3_2_0; }
		
		//("," camposTexto+=CampoTexto)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//camposTexto+=CampoTexto
		public Assignment getCamposTextoAssignment_3_3_1() { return cCamposTextoAssignment_3_3_1; }
		
		//CampoTexto
		public RuleCall getCamposTextoCampoTextoParserRuleCall_3_3_1_0() { return cCamposTextoCampoTextoParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('casillas' '{' casillasVerif+=CasillaVerif ("," casillasVerif+=CasillaVerif)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'casillas'
		public Keyword getCasillasKeyword_4_0() { return cCasillasKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//casillasVerif+=CasillaVerif
		public Assignment getCasillasVerifAssignment_4_2() { return cCasillasVerifAssignment_4_2; }
		
		//CasillaVerif
		public RuleCall getCasillasVerifCasillaVerifParserRuleCall_4_2_0() { return cCasillasVerifCasillaVerifParserRuleCall_4_2_0; }
		
		//("," casillasVerif+=CasillaVerif)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//casillasVerif+=CasillaVerif
		public Assignment getCasillasVerifAssignment_4_3_1() { return cCasillasVerifAssignment_4_3_1; }
		
		//CasillaVerif
		public RuleCall getCasillasVerifCasillaVerifParserRuleCall_4_3_1_0() { return cCasillasVerifCasillaVerifParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'botones'
		public Keyword getBotonesKeyword_5() { return cBotonesKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//botones+=Boton
		public Assignment getBotonesAssignment_7() { return cBotonesAssignment_7; }
		
		//Boton
		public RuleCall getBotonesBotonParserRuleCall_7_0() { return cBotonesBotonParserRuleCall_7_0; }
		
		//("," botones+=Boton)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//botones+=Boton
		public Assignment getBotonesAssignment_8_1() { return cBotonesAssignment_8_1; }
		
		//Boton
		public RuleCall getBotonesBotonParserRuleCall_8_1_0() { return cBotonesBotonParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//';'
		public Keyword getSemicolonKeyword_10() { return cSemicolonKeyword_10; }
	}
	public class CampoTextoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.CampoTexto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCampoTextoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTagAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTagEStringParserRuleCall_1_0 = (RuleCall)cTagAssignment_1.eContents().get(0);
		private final Assignment cOpcionalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cOpcionalOpcionalKeyword_2_0 = (Keyword)cOpcionalAssignment_2.eContents().get(0);
		
		//CampoTexto:
		//	'CampoTexto'
		//	tag=EString
		//	opcional?='opcional'?;
		@Override public ParserRule getRule() { return rule; }
		
		//'CampoTexto' tag=EString opcional?='opcional'?
		public Group getGroup() { return cGroup; }
		
		//'CampoTexto'
		public Keyword getCampoTextoKeyword_0() { return cCampoTextoKeyword_0; }
		
		//tag=EString
		public Assignment getTagAssignment_1() { return cTagAssignment_1; }
		
		//EString
		public RuleCall getTagEStringParserRuleCall_1_0() { return cTagEStringParserRuleCall_1_0; }
		
		//opcional?='opcional'?
		public Assignment getOpcionalAssignment_2() { return cOpcionalAssignment_2; }
		
		//'opcional'
		public Keyword getOpcionalOpcionalKeyword_2_0() { return cOpcionalOpcionalKeyword_2_0; }
	}
	public class CasillaVerifElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.CasillaVerif");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCasillaVerifKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cTagAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTagEStringParserRuleCall_2_0 = (RuleCall)cTagAssignment_2.eContents().get(0);
		private final Assignment cPorDefAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cPorDefSelectedKeyword_3_0 = (Keyword)cPorDefAssignment_3.eContents().get(0);
		
		//CasillaVerif:
		//	'CasillaVerif'
		//	name=EString
		//	tag=EString
		//	porDef?='selected'?;
		@Override public ParserRule getRule() { return rule; }
		
		//'CasillaVerif' name=EString tag=EString porDef?='selected'?
		public Group getGroup() { return cGroup; }
		
		//'CasillaVerif'
		public Keyword getCasillaVerifKeyword_0() { return cCasillaVerifKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//tag=EString
		public Assignment getTagAssignment_2() { return cTagAssignment_2; }
		
		//EString
		public RuleCall getTagEStringParserRuleCall_2_0() { return cTagEStringParserRuleCall_2_0; }
		
		//porDef?='selected'?
		public Assignment getPorDefAssignment_3() { return cPorDefAssignment_3; }
		
		//'selected'
		public Keyword getPorDefSelectedKeyword_3_0() { return cPorDefSelectedKeyword_3_0; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class BotonNavegarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.BotonNavegar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTagAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTagEStringParserRuleCall_0_0 = (RuleCall)cTagAssignment_0.eContents().get(0);
		private final Keyword cDestinosKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDestinoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDestinoDestinoParserRuleCall_3_0 = (RuleCall)cDestinoAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDestinoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDestinoDestinoParserRuleCall_4_1_0 = (RuleCall)cDestinoAssignment_4_1.eContents().get(0);
		
		//BotonNavegar:
		//	tag=EString
		//	'destinos' ':' destino+=Destino ("," destino+=Destino)*;
		@Override public ParserRule getRule() { return rule; }
		
		//tag=EString 'destinos' ':' destino+=Destino ("," destino+=Destino)*
		public Group getGroup() { return cGroup; }
		
		//tag=EString
		public Assignment getTagAssignment_0() { return cTagAssignment_0; }
		
		//EString
		public RuleCall getTagEStringParserRuleCall_0_0() { return cTagEStringParserRuleCall_0_0; }
		
		//'destinos'
		public Keyword getDestinosKeyword_1() { return cDestinosKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//destino+=Destino
		public Assignment getDestinoAssignment_3() { return cDestinoAssignment_3; }
		
		//Destino
		public RuleCall getDestinoDestinoParserRuleCall_3_0() { return cDestinoDestinoParserRuleCall_3_0; }
		
		//("," destino+=Destino)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//destino+=Destino
		public Assignment getDestinoAssignment_4_1() { return cDestinoAssignment_4_1; }
		
		//Destino
		public RuleCall getDestinoDestinoParserRuleCall_4_1_0() { return cDestinoDestinoParserRuleCall_4_1_0; }
	}
	public class BotonMensajeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.BotonMensaje");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTagAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTagEStringParserRuleCall_0_0 = (RuleCall)cTagAssignment_0.eContents().get(0);
		private final Keyword cMensajeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMensajeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMensajeEStringParserRuleCall_3_0 = (RuleCall)cMensajeAssignment_3.eContents().get(0);
		
		//BotonMensaje:
		//	tag=EString
		//	'mensaje' ':' mensaje=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//tag=EString 'mensaje' ':' mensaje=EString
		public Group getGroup() { return cGroup; }
		
		//tag=EString
		public Assignment getTagAssignment_0() { return cTagAssignment_0; }
		
		//EString
		public RuleCall getTagEStringParserRuleCall_0_0() { return cTagEStringParserRuleCall_0_0; }
		
		//'mensaje'
		public Keyword getMensajeKeyword_1() { return cMensajeKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//mensaje=EString
		public Assignment getMensajeAssignment_3() { return cMensajeAssignment_3; }
		
		//EString
		public RuleCall getMensajeEStringParserRuleCall_3_0() { return cMensajeEStringParserRuleCall_3_0; }
	}
	public class BotonCerrarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.BotonCerrar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBotonCerrarAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTagAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTagEStringParserRuleCall_1_0 = (RuleCall)cTagAssignment_1.eContents().get(0);
		
		//BotonCerrar:
		//	{BotonCerrar} tag=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{BotonCerrar} tag=EString
		public Group getGroup() { return cGroup; }
		
		//{BotonCerrar}
		public Action getBotonCerrarAction_0() { return cBotonCerrarAction_0; }
		
		//tag=EString
		public Assignment getTagAssignment_1() { return cTagAssignment_1; }
		
		//EString
		public RuleCall getTagEStringParserRuleCall_1_0() { return cTagEStringParserRuleCall_1_0; }
	}
	public class DestinoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "wizard.Wizard.Destino");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDestinoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDestinoPaginaCrossReference_1_0 = (CrossReference)cDestinoAssignment_1.eContents().get(0);
		private final RuleCall cDestinoPaginaEStringParserRuleCall_1_0_1 = (RuleCall)cDestinoPaginaCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCasillaAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cCasillaCasillaVerifCrossReference_2_1_0 = (CrossReference)cCasillaAssignment_2_1.eContents().get(0);
		private final RuleCall cCasillaCasillaVerifEStringParserRuleCall_2_1_0_1 = (RuleCall)cCasillaCasillaVerifCrossReference_2_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Destino:
		//	'(' destino=[Pagina|EString] (',' casilla=[CasillaVerif|EString])? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' destino=[Pagina|EString] (',' casilla=[CasillaVerif|EString])? ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//destino=[Pagina|EString]
		public Assignment getDestinoAssignment_1() { return cDestinoAssignment_1; }
		
		//[Pagina|EString]
		public CrossReference getDestinoPaginaCrossReference_1_0() { return cDestinoPaginaCrossReference_1_0; }
		
		//EString
		public RuleCall getDestinoPaginaEStringParserRuleCall_1_0_1() { return cDestinoPaginaEStringParserRuleCall_1_0_1; }
		
		//(',' casilla=[CasillaVerif|EString])?
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//casilla=[CasillaVerif|EString]
		public Assignment getCasillaAssignment_2_1() { return cCasillaAssignment_2_1; }
		
		//[CasillaVerif|EString]
		public CrossReference getCasillaCasillaVerifCrossReference_2_1_0() { return cCasillaCasillaVerifCrossReference_2_1_0; }
		
		//EString
		public RuleCall getCasillaCasillaVerifEStringParserRuleCall_2_1_0_1() { return cCasillaCasillaVerifEStringParserRuleCall_2_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	
	
	private final WizardElements pWizard;
	private final BotonElements pBoton;
	private final EStringElements pEString;
	private final PaginaElements pPagina;
	private final CampoTextoElements pCampoTexto;
	private final CasillaVerifElements pCasillaVerif;
	private final EBooleanElements pEBoolean;
	private final BotonNavegarElements pBotonNavegar;
	private final BotonMensajeElements pBotonMensaje;
	private final BotonCerrarElements pBotonCerrar;
	private final DestinoElements pDestino;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WizardGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWizard = new WizardElements();
		this.pBoton = new BotonElements();
		this.pEString = new EStringElements();
		this.pPagina = new PaginaElements();
		this.pCampoTexto = new CampoTextoElements();
		this.pCasillaVerif = new CasillaVerifElements();
		this.pEBoolean = new EBooleanElements();
		this.pBotonNavegar = new BotonNavegarElements();
		this.pBotonMensaje = new BotonMensajeElements();
		this.pBotonCerrar = new BotonCerrarElements();
		this.pDestino = new DestinoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("wizard.Wizard".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Wizard:
	//	'Wizard' titulo=EString
	//	'{'
	//	'Paginas:'
	//	paginas+=Pagina+
	//	'inicial' pagIni=[Pagina|EString]
	//	'}';
	public WizardElements getWizardAccess() {
		return pWizard;
	}
	
	public ParserRule getWizardRule() {
		return getWizardAccess().getRule();
	}
	
	//Boton:
	//	"Boton" "navegar" BotonNavegar | "Boton" "mensaje" BotonMensaje | "Boton" "cerrar" BotonCerrar;
	public BotonElements getBotonAccess() {
		return pBoton;
	}
	
	public ParserRule getBotonRule() {
		return getBotonAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Pagina:
	//	'Pagina'
	//	name=EString
	//	':' ('campos' '{' camposTexto+=CampoTexto ("," camposTexto+=CampoTexto)* '}')? ('casillas' '{'
	//	casillasVerif+=CasillaVerif ("," casillasVerif+=CasillaVerif)* '}')?
	//	'botones' '{' botones+=Boton ("," botones+=Boton)* '}'
	//	';';
	public PaginaElements getPaginaAccess() {
		return pPagina;
	}
	
	public ParserRule getPaginaRule() {
		return getPaginaAccess().getRule();
	}
	
	//CampoTexto:
	//	'CampoTexto'
	//	tag=EString
	//	opcional?='opcional'?;
	public CampoTextoElements getCampoTextoAccess() {
		return pCampoTexto;
	}
	
	public ParserRule getCampoTextoRule() {
		return getCampoTextoAccess().getRule();
	}
	
	//CasillaVerif:
	//	'CasillaVerif'
	//	name=EString
	//	tag=EString
	//	porDef?='selected'?;
	public CasillaVerifElements getCasillaVerifAccess() {
		return pCasillaVerif;
	}
	
	public ParserRule getCasillaVerifRule() {
		return getCasillaVerifAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//BotonNavegar:
	//	tag=EString
	//	'destinos' ':' destino+=Destino ("," destino+=Destino)*;
	public BotonNavegarElements getBotonNavegarAccess() {
		return pBotonNavegar;
	}
	
	public ParserRule getBotonNavegarRule() {
		return getBotonNavegarAccess().getRule();
	}
	
	//BotonMensaje:
	//	tag=EString
	//	'mensaje' ':' mensaje=EString;
	public BotonMensajeElements getBotonMensajeAccess() {
		return pBotonMensaje;
	}
	
	public ParserRule getBotonMensajeRule() {
		return getBotonMensajeAccess().getRule();
	}
	
	//BotonCerrar:
	//	{BotonCerrar} tag=EString;
	public BotonCerrarElements getBotonCerrarAccess() {
		return pBotonCerrar;
	}
	
	public ParserRule getBotonCerrarRule() {
		return getBotonCerrarAccess().getRule();
	}
	
	//Destino:
	//	'(' destino=[Pagina|EString] (',' casilla=[CasillaVerif|EString])? ')';
	public DestinoElements getDestinoAccess() {
		return pDestino;
	}
	
	public ParserRule getDestinoRule() {
		return getDestinoAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
