/*
 * generated by Xtext 2.15.0
 */
package wizard.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import wizard.texteditor.ui.internal.TexteditorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WizardExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TexteditorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TexteditorActivator activator = TexteditorActivator.getInstance();
		return activator != null ? activator.getInjector(TexteditorActivator.WIZARD_WIZARD) : null;
	}

}
