/**
 * generated by Xtext 2.15.0
 */
package wizard.ui.contentassist;

import wizard.ui.contentassist.AbstractWizardProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WizardProposalProvider extends AbstractWizardProposalProvider {
}
