/*
 * generated by Xtext 2.15.0
 */
package wizard.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import wizard.WizardRuntimeModule
import wizard.WizardStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class WizardIdeSetup extends WizardStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new WizardRuntimeModule, new WizardIdeModule))
	}
	
}
