/**
 * generated by Xtext 2.15.0
 */
package wizard.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import wizard.ui.AbstractWizardUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WizardUiModule extends AbstractWizardUiModule {
  public WizardUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
